name: MobileSwift

options:
  minimumXcodeGenVersion: 2.39.0

packages:
  Nuke:
    url: https://github.com/kean/Nuke
    from: "12.8.0"
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.5.0"

targets:
  MobileSwift:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    info:
      path: Sources/Info.plist
    sources:
      - Sources
    configFiles:
      Debug: Config/App.xcconfig
      Release: Config/App.xcconfig
    dependencies:
      - package: Nuke
        product: NukeUI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moviemanager.mobileswift
        PRODUCT_NAME: MobileSwift
        SWIFT_VERSION: 6.0
        TARGETED_DEVICE_FAMILY: "1"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Sources/Info.plist
        INFOPLIST_EXPAND_BUILD_SETTINGS: YES
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

schemes:
  MobileSwift:
    build:
      targets:
        MobileSwift: all
    run:
      config: Debug
    archive:
      config: Release
