server {
	listen 80 default_server;
	server_name _;

	location = /health {
		add_header Content-Type text/plain;
		return 200 "yeah dude im healthy\n";
	}

	location / {
		add_header Content-Type text/plain;
		return 200 "Mac Mini nginx @ 192.168.1.69\n";
	}
}
