"""initial tables

Revision ID: 613443aa237d
Revises: 
Create Date: 2026-02-03 23:20:47.363600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613443aa237d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('tmdb_data', sa.Text(), nullable=True),
    sa.Column('omdb_data', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('imdb_id')
    )
    op.create_index(op.f('ix_movies_imdb_id'), 'movies', ['imdb_id'], unique=False)
    op.create_table('people',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('movie_status',
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('toWatch', 'watched', 'questionable', 'deleted')", name='check_status_values'),
    sa.ForeignKeyConstraint(['imdb_id'], ['movies.imdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('imdb_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('person', sa.String(), nullable=False),
    sa.Column('date_recommended', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['imdb_id'], ['movies.imdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch_history',
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('date_watched', sa.Float(), nullable=False),
    sa.Column('my_rating', sa.Float(), nullable=False),
    sa.CheckConstraint('my_rating >= 1.0 AND my_rating <= 10.0', name='check_rating_range'),
    sa.ForeignKeyConstraint(['imdb_id'], ['movies.imdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('imdb_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_history')
    op.drop_table('recommendations')
    op.drop_table('movie_status')
    op.drop_table('people')
    op.drop_index(op.f('ix_movies_imdb_id'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
