"""initial_with_users

Revision ID: ffede2f75426
Revises: 
Create Date: 2026-02-03 17:55:18.338564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffede2f75426'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('movies',
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tmdb_data', sa.Text(), nullable=True),
    sa.Column('omdb_data', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('imdb_id', 'user_id')
    )
    op.create_index(op.f('ix_movies_imdb_id'), 'movies', ['imdb_id'], unique=False)
    op.create_table('people',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'user_id')
    )
    op.create_table('movie_status',
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('toWatch', 'watched', 'questionable', 'deleted')", name='check_status_values'),
    sa.ForeignKeyConstraint(['imdb_id', 'user_id'], ['movies.imdb_id', 'movies.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('imdb_id', 'user_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('person', sa.String(), nullable=False),
    sa.Column('date_recommended', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['imdb_id', 'user_id'], ['movies.imdb_id', 'movies.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch_history',
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date_watched', sa.Float(), nullable=False),
    sa.Column('my_rating', sa.Float(), nullable=False),
    sa.CheckConstraint('my_rating >= 1.0 AND my_rating <= 10.0', name='check_rating_range'),
    sa.ForeignKeyConstraint(['imdb_id', 'user_id'], ['movies.imdb_id', 'movies.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('imdb_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_history')
    op.drop_table('recommendations')
    op.drop_table('movie_status')
    op.drop_table('people')
    op.drop_index(op.f('ix_movies_imdb_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
