name: SwiftTestApp

options:
  minimumXcodeGenVersion: 2.39.0

targets:
  SwiftTestApp:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - Sources
    info:
      path: Sources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moviemanager.swifttest
        PRODUCT_NAME: SwiftTestApp
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

schemes:
  SwiftTestApp:
    build:
      targets:
        SwiftTestApp: all
    run:
      config: Debug
    archive:
      config: Release
