name: Landmarks

options:
  minimumXcodeGenVersion: 2.39.0

targets:
  Landmarks:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: .
        includes:
          - "**/*.swift"
    resources:
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.landmarks
        PRODUCT_NAME: Landmarks
        SWIFT_VERSION: 6.0
        TARGETED_DEVICE_FAMILY: "1,2"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Landmarks
        INFOPLIST_KEY_LSRequiresIPhoneOS: YES
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Landmarks uses your location to show nearby places on the map."
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic

schemes:
  Landmarks:
    build:
      targets:
        Landmarks: all
    run:
      config: Debug
    archive:
      config: Release
