import Foundation

// Placeholder typed localization symbols so the app builds without an .xcstrings catalog.
extension LocalizedStringResource {
    enum LandmarkData {
        static let alpsDescription = LocalizedStringResource("alpsDescription")
        static let alpsLocation = LocalizedStringResource("alpsLocation")
        static let alpsName = LocalizedStringResource("alpsName")
        static let amazonRainforestDescription = LocalizedStringResource("amazonRainforestDescription")
        static let amazonRainforestLocation = LocalizedStringResource("amazonRainforestLocation")
        static let amazonRainforestName = LocalizedStringResource("amazonRainforestName")
        static let deadvleiDescription = LocalizedStringResource("deadvleiDescription")
        static let deadvleiLocation = LocalizedStringResource("deadvleiLocation")
        static let deadvleiName = LocalizedStringResource("deadvleiName")
        static let grandCanyonDescription = LocalizedStringResource("grandCanyonDescription")
        static let grandCanyonLocation = LocalizedStringResource("grandCanyonLocation")
        static let grandCanyonName = LocalizedStringResource("grandCanyonName")
        static let greatBarrierReefDescription = LocalizedStringResource("greatBarrierReefDescription")
        static let greatBarrierReefLocation = LocalizedStringResource("greatBarrierReefLocation")
        static let greatBarrierReefName = LocalizedStringResource("greatBarrierReefName")
        static let joshuaTreeDescription = LocalizedStringResource("joshuaTreeDescription")
        static let joshuaTreeLocation = LocalizedStringResource("joshuaTreeLocation")
        static let joshuaTreeName = LocalizedStringResource("joshuaTreeName")
        static let kirkjufellMountainDescription = LocalizedStringResource("kirkjufellMountainDescription")
        static let kirkjufellMountainLocation = LocalizedStringResource("kirkjufellMountainLocation")
        static let kirkjufellMountainName = LocalizedStringResource("kirkjufellMountainName")
        static let lençóisMaranhensesDescription = LocalizedStringResource("lençóisMaranhensesDescription")
        static let lençóisMaranhensesLocation = LocalizedStringResource("lençóisMaranhensesLocation")
        static let lençóisMaranhensesName = LocalizedStringResource("lençóisMaranhensesName")
        static let monumentValleyDescription = LocalizedStringResource("monumentValleyDescription")
        static let monumentValleyLocation = LocalizedStringResource("monumentValleyLocation")
        static let monumentValleyName = LocalizedStringResource("monumentValleyName")
        static let mountEverestDescription = LocalizedStringResource("mountEverestDescription")
        static let mountEverestLocation = LocalizedStringResource("mountEverestLocation")
        static let mountEverestName = LocalizedStringResource("mountEverestName")
        static let mountFujiDescription = LocalizedStringResource("mountFujiDescription")
        static let mountFujiLocation = LocalizedStringResource("mountFujiLocation")
        static let mountFujiName = LocalizedStringResource("mountFujiName")
        static let muirWoodsDescription = LocalizedStringResource("muirWoodsDescription")
        static let muirWoodsLocation = LocalizedStringResource("muirWoodsLocation")
        static let muirWoodsName = LocalizedStringResource("muirWoodsName")
        static let niagaraFallsDescription = LocalizedStringResource("niagaraFallsDescription")
        static let niagaraFallsLocation = LocalizedStringResource("niagaraFallsLocation")
        static let niagaraFallsName = LocalizedStringResource("niagaraFallsName")
        static let rockyMountainsDescription = LocalizedStringResource("rockyMountainsDescription")
        static let rockyMountainsLocation = LocalizedStringResource("rockyMountainsLocation")
        static let rockyMountainsName = LocalizedStringResource("rockyMountainsName")
        static let saharaDesertDescription = LocalizedStringResource("saharaDesertDescription")
        static let saharaDesertLocation = LocalizedStringResource("saharaDesertLocation")
        static let saharaDesertName = LocalizedStringResource("saharaDesertName")
        static let serengetiDescription = LocalizedStringResource("serengetiDescription")
        static let serengetiLocation = LocalizedStringResource("serengetiLocation")
        static let serengetiName = LocalizedStringResource("serengetiName")
        static let southShetlandIslandsDescription = LocalizedStringResource("southShetlandIslandsDescription")
        static let southShetlandIslandsLocation = LocalizedStringResource("southShetlandIslandsLocation")
        static let southShetlandIslandsName = LocalizedStringResource("southShetlandIslandsName")
        static let uyuniSaltFlatDescription = LocalizedStringResource("uyuniSaltFlatDescription")
        static let uyuniSaltFlatLocation = LocalizedStringResource("uyuniSaltFlatLocation")
        static let uyuniSaltFlatName = LocalizedStringResource("uyuniSaltFlatName")
        static let whiteCliffsOfDoverDescription = LocalizedStringResource("whiteCliffsOfDoverDescription")
        static let whiteCliffsOfDoverLocation = LocalizedStringResource("whiteCliffsOfDoverLocation")
        static let whiteCliffsOfDoverName = LocalizedStringResource("whiteCliffsOfDoverName")
        static let wulingyuanDescription = LocalizedStringResource("wulingyuanDescription")
        static let wulingyuanLocation = LocalizedStringResource("wulingyuanLocation")
        static let wulingyuanName = LocalizedStringResource("wulingyuanName")
        static let yellowstoneNationalParkDescription = LocalizedStringResource("yellowstoneNationalParkDescription")
        static let yellowstoneNationalParkLocation = LocalizedStringResource("yellowstoneNationalParkLocation")
        static let yellowstoneNationalParkName = LocalizedStringResource("yellowstoneNationalParkName")
    }

    enum LandmarkCollectionData {
        static let _2023TripDescription = LocalizedStringResource("_2023TripDescription")
        static let _2023TripName = LocalizedStringResource("_2023TripName")
        static let favoritesName = LocalizedStringResource("favoritesName")
        static let icyWonderlandDescription = LocalizedStringResource("icyWonderlandDescription")
        static let icyWonderlandName = LocalizedStringResource("icyWonderlandName")
        static let sweetDesertsDescription = LocalizedStringResource("sweetDesertsDescription")
        static let sweetDesertsName = LocalizedStringResource("sweetDesertsName")
        static let toweringPeaksDescription = LocalizedStringResource("toweringPeaksDescription")
        static let toweringPeaksName = LocalizedStringResource("toweringPeaksName")
    }
}
